### PR TITLE
Specify the architecture to avoid confusion #7

### PR DESCRIPTION
**Pull request by Yakov5776**

### CODE REVIEW

**Comment by WackyH-OS** [comment]
Unrelated, but my problem still isnt solved, I've installed both x86 and x64 versions, and I still get the error, what is wrong?

**Comment by Yakov5776** [comment]
Have you restarted?

**Comment by WackyH-OS** [comment]
Yup. Even tried compatability mode with Vista. Still doesn't work.

**Comment by Yakov5776** [comment]
You're gonna have to ask david baszucki yourself or someone else who knows why lol

**Comment by WackyH-OS** [comment]
Heh. Is there anything else I can try to actually get this to work?

**Comment by Yakov5776** [comment]
I mean getting those redistributable's are suppose to work

**Comment by WackyH-OS** [comment]
wait, do i install the MFC security one or ATL security update one?

**Pull request merged**
