### PR TITLE
update mesa 7.0 dlls

### PR DESCRIPTION
**Pull request by pizzaboxer**
forgot to compile as release lol

### CODE REVIEW

**Comment by Mantaraix** [comment]
Actual nerd

**Comment by pizzaboxer** [comment]
fuk u

**Comment by CloneTrooper1019** [comment]
Studio seems to crash with these DLLs in place, is there any other special requirement to get this running?
Maybe shadows need to be disabled?

**Comment by CloneTrooper1019** [comment]
Can confirm that was the issue.

**Pull request merged**
